spring:
  application:
    name: hk-crowd-pay
  redis:
    host: 192.168.200.130
  session:
    store-type: redis
server:
  port: 10000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
ali:
  pay:
    app-id: 2021000119603521
    merchantPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDV8wUHsomGnGz7GcgN3ubDKCBqBfCsawfWckN+gskcWSatCjlEIsJSEwbJEzmwG24FbBY91Qo7uno3l0ll3WfOj02D/AeDS5PyZmeZbUn6Zvq4UmSy91mcxkufokoM9PsvRjt2G3aw4Noq85h8Z5ecQpHsyt9SJ9Q7POWd2Jfn44/N2lj7ilouz2k+6i6REFAVnN9V+yPPFB1tFUDx94JdNFwv1cVXu3XTJ7tT/9i18N+pQzYNBeCKzeoUH5xca2qrX8pDb2xx5CZ6N6mC2hLQIrjAvQleKG+8qooe5Cabu7xFdFUDDTuMLliN0y0JYsmfNqz+fiWEobqS47WCaq5nAgMBAAECggEAbQhvfM/BBIf9hi5KZL8/DSAK/N1QHR5inSgYO4X9ZeQNMMxwCMhKDbfCkoCoupYQCNVftF043N2Y4XHJJw+hkoQ3ddbgIUpH+JW1oFwxAlqu1Xav+QDTe3EXIyB66oWC6UG6leNDJrtAk/kWsfe9LRZD9dAh5WWE5DeRsVKrf7Hri837+ttdeiidIQoTy8BcKPU6SSo1OlSTYiC5Uft/Ii/ZdAv4mBU9fYw/xYYje0RekrW+3t9zv2x1QmoqBTMxWA6ADAU6KEbJkPcCgP8b2AlLGHzGnrSWCgr89JNP99SFhFdq1fsXucd5bbuOManmHxpXWnCyC9iYaZFmiXUUYQKBgQDtiLsIwNwzPkSOW85QvpGVNtTvOUcmTswCG8+dxvzs4hTp/NI9yfxAdZYTVCUzzxt1qzMpbDOdFRaeg79xZYgETu0JyCQvImjAgRsxHu9+tekDhol1vqmo89dns8VSvYnfwt0OlUDMVDZ/dWjUm140qcMft0qVvjIbRLqYXBOV8QKBgQDmlOrjGvHoQny2CXZh748kJSwnlnDflLPU10q/FfCqJd+7BEEwT7dVC9EwKwnvwQYaSs0dbr57upNtBbD9qXyKVpftBLNR3x1xdP6cpS2h3hPxI0y7ZnGcM31BxW8TL8S/tNubOP7hILA11Nd+gd6I8qhl2f/L/IesOiI2827R1wKBgFQdn14yLchXvJ9NE3q0gYl9qVotxmxiaww0HQmadebNCOrzhOAsrw+ElGiz25jFNswsnCmHD6AI38GylhDqC4i7CmX0Yhvu63mAPsjeU6Fjeeits+/mXN5fu2AV4UKzrCd5Mh7/67pv9/ya70ya2Hl9xINuvRLaD5RoekuKD8WBAoGBAIS49RbyHIo/Mv+pJK4ssSzyBJ9o1eGr+3Mo1Up2O4gEsuo4AbnoOLPIUIm0TEznwzaBFd26MASSGWfonb70vs32GA8C5KDcl1sGJ8RMw55ncP0c/37i8cQiUxf3p/7YQRzD4qBPR06YfTUPJVcZM9mKK2os+DMXUZTOBYGxz3kTAoGAZpATwIqiDj80soCxIxWPoPm+E99naaUsko46wS69UQJoX/eEsCrYNbdRDKhsAikXn0ei49ZXl3vRFqey3VVv49sTEQxLW6xVOoWKOvkSSR70So5ZNgQnRXOqwqRrVayLoioeJwCSX313yoejQEuzKEq18FS9zQt8zqX2Eec1eZs=
    alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAi5h2/HeDWRV3py/x8/W8uKHlrp9M/yOtXYAVJtIPUSNhiFxQ9kyli7Wwyac4zKDnrKE2VKwEyfDZQfWpAparjCDbMHrUpZZhuv1KxnzENElGjag6VNclu/lf2CVC60q22uzaFzVWpPX8jT65LsCWjVqvI/Oju7ptPKIREGxkvgCUn4I0zYC1J2pt2wgmR8SDxfcMaXAyrwjtYL2YT+Do2k3hGxjc6+GjjoMYkvdWHJA/+eA+JCcnJB5YvtPxILM3BbhLup7dXanuos5MJ8R47miKBHrG25v/bErE2kZR7O+NoTTShm/X4XOU0WvxGaybdvcjlIJg59HzNqKM7bJZ3QIDAQAB
    charset: utf-8
    gateway-url: https://openapi.alipaydev.com/gateway.do
    notify-url: http://hpif4d.natappfree.cc/pay/notify
    return-url: http://localhost/pay/return
    sign-type: RSA2