spring:
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/project_crowd?serverTimezone=UTC
    username: root
    password: 915+sxl..
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: hk-crowd-mysql
mybatis:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
logging:
  level:
    com.hk.crowd.mapper: debug
    com.hk.crowd.test: debug
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
server:
  port: 2000