server:
  port: 80
spring:
  application:
    name: hk-crowd-zuul
  redis:
    host: 192.168.200.130
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
zuul:
  ignored-services: "*"
  sensitive-headers: "*" # 在 Zuul 向其他微服务重定向时保持原本头信息（请求头、响应头）
  routes:
    crowd-portal:
      service-id: hk-crowd-auth
      path: /** #访问多层路径
    crowd-project:
      service-id: hk-crowd-project
      path: /project/**
    crowd-order:
      service-id: hk-crowd-order
      path: /order/**
    crowd-pay:
      service-id: hk-crowd-pay
      path: /pay/**
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000